# Job de notificación en caso de fallo
 notify_failure:
 runs-on: ubuntu-latest
 needs: [test, deploy] # Se ejecuta después de ambos jobs
 if: failure() # Solo se ejecuta si cualquiera de los jobs anteriores falla
 steps:
 - name: Send email notification on failure
 env:
 SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
 TO_EMAIL: ${{ secrets.TO_EMAIL }}
 FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
 run: |
 curl -X POST \
 --url https://api.sendgrid.com/v3/mail/send \
 -H "Authorization: Bearer $SENDGRID_API_KEY" \
 -H "Content-Type: application/json" \
 -d '{
 "personalizations": [{
 "to": [{"email": "'jimenezhernandezeriksantiago@gmail.com'"}],
 "subject": "GitHub Actions Job Failed"
 }],
 "from": {"email": "'jimenezhernandezeriksantiago@gmail.com'"},
 "content": [{
 "type": "text/plain",
 "value": "El flujo de trabajo en GitHub Actions falló. Por favor revisa los detalles 
en la pestaña de Actions en GitHub."
 }]
 }'
